name: Common CI

on:
  push:
    branches-ignore:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: git fetch --no-tags --prune --depth=5 origin develop

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build affected applications
        run: yarn affected:build --base=origin/develop

      - name: Lint affected applications
        run: yarn affected:lint --base=origin/develop

      - name: Test affected applications
        run: yarn affected:test --base=origin/develop
