# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Develop CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: git fetch --no-tags --prune --depth=5 origin develop
      - run: yarn install --frozen-lockfile
      - run: yarn affected:build --base=develop~1 --head=develop
      - run: yarn affected:lint --base=develop~1 --head=develop
      - run: yarn affected:test --base=develop~1 --head=develop

      - name: Configure Elastic Beanstalk CLI
        uses: jhowr/actions-aws-eb@v1.0.0
        with:
          command: 'yarn affected:deploy --base=develop~1 --head=develop --profile_name=eb-cicd-user'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'sa-east-1'
