name: User Develop CI

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/user/**'
      - 'libs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Set microservice app name
        id: set-ms-app-name
        run: echo "::set-output name=MS_APP_NAME::user"

      - name: Set IAM user name
        id: set-iam-user-name
        run: echo "::set-output name=AWS_IAM_USER_NAME::eb-cicd-user"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build affected applications
        run: yarn affected:build --base=develop~1 --head=develop

      - name: Lint affected applications
        run: yarn affected:lint --base=develop~1 --head=develop

      - name: Test affected applications
        run: yarn affected:test --base=develop~1 --head=develop

      - name: Deploy preparation
        run: |
          cp ./package.json ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/package.json
      #          mkdir -p ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/.elasticbeanstalk
      #          cp ./.deploy/dev.config.yml ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/.elasticbeanstalk/config.yml
      #          sed -i 's/$APPLICATION_NAME/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/g' ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/.elasticbeanstalk/config.yml
      #          sed -i 's/$PROFILE_NAME/${{ steps.set-iam-user-name.outputs.AWS_IAM_USER_NAME }}/g' ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/.elasticbeanstalk/config.yml

      - name: Check Current Folder
        run: |
          ls -all

      - name: Deploy to Elastic Beanstalk
        uses: jhowr/actions-aws-eb@v1.1.3
        with:
          dir: 'dist/apps/user'
          profile: 'eb-cicd-user'
          region: 'sa-east-1'
          application_name: 'monorepo-nx-user'
          command: 'deploy monorepo-nx-user-dev --profile=eb-cicd-user --debug'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'sa-east-1'
