name: User Develop CI

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/user/**'
      - 'libs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Set microservice app name
        id: set-ms-app-name
        run: echo "::set-output name=MS_APP_NAME::user"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build affected applications
        run: yarn affected:build --base=develop~1 --head=develop

      - name: Lint affected applications
        run: yarn affected:lint --base=develop~1 --head=develop

      - name: Test affected applications
        run: yarn affected:test --base=develop~1 --head=develop

      - name: Deploy preparation
        run: |
          cp ./package.json ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/package.json
          mkdir -p ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/.elasticbeanstalk
          cp ./.deploy/dev.config.yml ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/.elasticbeanstalk/config.yml
          sed -i 's/$APPLICATION_NAME/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/g' ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/.elasticbeanstalk/config.yml
          sed -i 's/$PROFILE_NAME/${{ secrets.AWS_EB_IAM_USER_NAME }}/g' ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}/.elasticbeanstalk/config.yml
          cd ./dist/apps/${{ steps.set-ms-app-name.outputs.MS_APP_NAME }}

      - name: Check Current Folder
        run: |
          ls -all

      - name: Deploy to Elastic Beanstalk
        uses: jhowr/actions-aws-eb@v1.0.0
        with:
          command: 'deploy monorepo-nx-user-dev'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'sa-east-1'
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: sa-east-1

#      - run: git fetch --no-tags --prune --depth=5 origin develop
#      - run: yarn install --frozen-lockfile
#      - run: yarn affected:build --base=develop~1 --head=develop
#      - run: yarn affected:lint --base=develop~1 --head=develop
#      - run: yarn affected:test --base=develop~1 --head=develop
#      - run: yarn affected:deploy --base=develop~1 --head=develop --profile_name=eb-cicd-user
